name: test workflow
on:
  workflow_call:
    inputs:
      name:
        description: "Job name"
        required: true
        type: string

permissions:
  contents: write

jobs:
  reusable:
    name: Run Job
    runs-on: ubuntu-22.04
    steps:
      - run: echo "JOB ${{inputs.name}}"
