name: Test shared manually triggered workflows
on:
  workflow_dispatch:
    inputs:
        version:
          description: "The version to release, without the leading `v`"
          required: true
          type: string
        previous_version:
          description: "The previous version, used for the CVS's `replaces` field, without the leading `v`"
          required: true
          type: string

jobs:
  test-job:
    runs-on: ubuntu-22.04
    steps:
      - name: step 1
        run: |
          echo "Hello World"
